// templates/react/src/pages/index.tsx
import { useEffect, useLayoutEffect, useState } from 'react';
import { useSnapshot } from 'valtio';
import { sampleStore } from '../store/sample';
import SvgIcon from '../svg-icons/SvgIcon';

export default function Index() {
  const sample = useSnapshot(sampleStore);
  const changeNumber = () => {
    const randomNumber = Math.random();
    sampleStore.randomNumber = randomNumber;
  };

  return (
    <div className="flex flex-col gap-4">
      <p className="text-4">/pages/_index.tsx</p>
      <p className="text-4">Store randomNumber = {sample.randomNumber}</p>

      <div>
        <button type="button" className="flex gap-2 items-center rounded px-4 py-2" onClick={changeNumber}>
          <SvgIcon icon="sample/random" className="w-6 h-6" />
          Random Number
        </button>
      </div>
    </div>
  );
}

// templates/vue/src/pages/index.vue
<script setup lang="ts">
import { reactive } from 'vue';
import { useSampleStore } from '../store/sample';
import SvgIcon from '../svg-icons/SvgIcon.vue';

const sample = useSampleStore();

function changeNumber() {
  sample.randomNumber = Math.random();
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <p class="text-4">
      /pages/index.tsx
    </p>
    <p class="text-4">
      Store randomNumber = {{ sample.randomNumber }}
    </p>

    <div>
      <button type="button" class="flex gap-2 items-center rounded px-4 py-2" @click="changeNumber()">
        <SvgIcon icon="sample/random" class="w-6 h-6" />
        Random Number
      </button>
    </div>
  </div>
</template>
